name: Build & Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: build image
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v5
      
      with:
        context: .
        file: ./Whiteboard.Service/Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}
