name: Build & Deploy

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: cloudbordcontainer.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: build image
      run: docker build . -t cloudbordcontainer.azurecr.io/whiteboard-service
    - name: deploy
      run: docker push cloudbordcontainer.azurecr.io/whiteboard-service
