# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup testing database
      env:
        CONNECTIONSTRINGS__NPGSQL: ${{ secrets.CONNECTIONSTRINGS_NPGSQL_TEST }}
      run: docker run -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres
    - name: Setup Entity Framework tool
      run: dotnet tool install --global dotnet-ef
    - name: Run migrations
      run: dotnet ef database update --startup-project Whiteboard.Service --project Whiteboard.DataAccess
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
